version: '2'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=geek_beacon
      - POSTGRES_PASSWORD=geek_beacon
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - ./volumes/postgres_data_local:/var/lib/postgresql/data
      - ./volumes/postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=geek_beacon
      - POSTGRES_PASSWORD=geek_beacon
    ports:
      - "5432:5432"



  redis:
    image: redis:3.0

  celeryworker:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh

