version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
    env_file: .env
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  www:
    image: geekbeacon/nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    container_name: www_web
    ports:
      - "8000:80"
    volumes:
      - ./compose/production/nginx/config:/etc/nginx/conf.d
    depends_on:
      - django

