name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: create symlink
      run: ln -s production.yml docker-compose.yml && cp env.example .env
    - name: Build the Docker image
      run: docker-compose build 
